spring.main.allow-bean-definition-overriding: true
spring.main.allow-circular-references: true
spring:
  profiles:
    include: security
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

